# Generated by Django 3.0.8 on 2020-07-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'accounttype',
            },
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
        migrations.DeleteModel(
            name='TableColumn',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='school_class',
            new_name='course',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
