# Generated by Django 3.0.8 on 2020-07-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.AccountType'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
    ]
